const PAYMAYA_WEBHOOK_STATUS = {
  SUCCESS: 'PAYMENT_SUCCESS',
  FAILED: 'PAYMENT_FAILED',
  EXPIRED: 'PAYMENT_EXPIRED',
  CANCELLED: 'PAYMENT_CANCELLED',
  AUTHORIZED: 'PAYMENT_AUTHORIZED',
};

export type PaymayaWebhookStatus =
  (typeof PAYMAYA_WEBHOOK_STATUS)[keyof typeof PAYMAYA_WEBHOOK_STATUS];
