// note: this staging are parent staging or status and cannot be edited
export enum TransactionStaging {
  IN_PROCESS = 'IN_PROCESS',
  FOR_CLIENT_RESUBMISSION = 'FOR_CLIENT_RESUBMISSION',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  FOR_DOCUMENT_REVIEW = 'FOR_DOCUMENT_REVIEW',
  FOR_EOS_APPROVAL = 'FOR_EOS_APPROVAL',
  FOR_SALES_REVIEW = 'FOR_SALES_REVIEW',
  SUCCESS_OUTPUT = 'SUCCESS_OUTPUT',
  CLOSED = 'CLOSED',
  CANCELED = 'CANCELED',
  ON_HOLD = 'ON_HOLD',
}
